collections:
  datasets:
      output: true
  people:
    output: true
  article:
    output: true
  algorithm:
    output: true


defaults:
  - scope:
      path: ""
      type: "articles"
    values:
      layout: "article"
  - scope:
      path: ""
      type: "datasets"
    values:
      layout: "datasets"
  - scope:
      path: ""
      type: "people"
    values:
      layout: "people"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "algorithms"
    values:
      layout: "algorithm"
theme: jekyll-theme-architect