
baseurl: ''

# Site settings
title: Brain2Speech
email:


# Team names, titles and social links
people:

- name: Sid Fels
  pic: icon
  position: Professor and Lab Director
  email: ssfels@ece.ubc.ca

- name: test 1
  pic: icon
  position:
  email:


- name: test 2
  pic: icon
  position:
  email:


- name: test3
  pic: icon
  position:
  email:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/hctlab
  - title: globe
    url: http://hct.ece.ubc.ca/
  - title: github
    url: https://github.com/Brain2Speech

# Postal address (add as many lines as necessary)
address:
  - line: x427/x509, ICICS X-Wing
  - line: 2366 Main Mall
  - line: Vancouver, BC Canada V6T 1Z4

# Build settings
markdown: kramdown
permalink: none

collections:
  algorithms:
    output: true
  datasets:
    output: true
