
baseurl: ''

# Site settings
title: Brain2Speech
email:


# Team names, titles and social links
people:

- name: Sid Fels
  pic: icon
  position: Professor and Lab Director
  email: ssfels@ece.ubc.ca
  social:
  -  title: globe
     url: http://hct.ece.ubc.ca/person/sid-fels/


- name: Debasish Ray Mohapatra
  pic: icon
  position: MASc Student
  email: d.mohapatra@alumni.ubc.ca
  social:
    - title: github
      url:



- name: Praneeth SV
  pic: icon
  position: MASc Student
  email: praneethsv@ece.ubc.ca
  social:
    - title: github
      url:



- name: Pramit Saha
  pic: icon
  position: MASc Studennt
  email: pramitsaha.juee@gmail.com
  social:
  - title: github
    url:

- name: Irene Wang
  pic: icon
  position: Website Coordinator
  email: irene.wang.05@alumni.ubc.ca
  social:
  - title: github
    url: https://github.com/iwang05
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/hctlab
  - title: globe
    url: http://hct.ece.ubc.ca/
  - title: github
    url: https://github.com/Brain2Speech

# Postal address (add as many lines as necessary)
address:
  - line: x427/x509, ICICS X-Wing
  - line: 2366 Main Mall
  - line: Vancouver, BC Canada V6T 1Z4

# Build settings
markdown: kramdown
permalink: none

collections:
  algorithms:
    output: true
  datasets:
    output: true
